openapi: 3.0.3
info:
  title: Authentication API
  description: API for user login authentication.
  version: 1.0.0
paths:
  /v1/auth/login:
    post:
      summary: User login
      description: Authenticates a user and returns an access token.
      operationId: loginUser
      tags:
        - Authentication
      requestBody:
        description: User login credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                  example: "user@example.com"
                password:
                  type: string
                  format: password
                  description: User's password
                  example: "P@ssw0rd!"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: JWT access token
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                  refreshToken:
                    type: string
                    description: Refresh token for generating new access tokens
                    example: "dGhpc1JvbmRvbVJlZnJlc2hUb2tlbi4uLg=="
                  expiresIn:
                    type: integer
                    description: Access token expiration time in seconds
                    example: 3600
                  tokenType:
                    type: string
                    description: Type of token returned
                    example: "Bearer"
        "400":
          description: Invalid login credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    description: Error code indicating the issue
                    example: "INVALID_CREDENTIALS"
                  message:
                    type: string
                    description: Error message
                    example: "Invalid email or password."
        "401":
          description: Unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    description: Error code indicating the issue
                    example: "UNAUTHORIZED"
                  message:
                    type: string
                    description: Error message
                    example: "Unauthorized access."
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorCode:
                    type: string
                    description: Error code indicating the issue
                    example: "SERVER_ERROR"
                  message:
                    type: string
                    description: Error message
                    example: "An unexpected error occurred. Please try again later."
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []
